# Generated by Django 5.1.3 on 2024-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('ibge', models.CharField(blank=True, max_length=7, null=True)),
                ('gia', models.CharField(blank=True, max_length=4, null=True)),
                ('ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('siafi', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
